### ISSUE TITLE
TOC below ON THIS PAGE has same color as bckg (white)

### ISSUE THREAD

**Issue by rcastelo** [Bioconductor/EuroBioC2025#3]
The floating table of contents below "ON THIS PAGE" has the same color as the background (white) and cannot be read, except the option hovered by the mouse.

**Comment by HelenaLC** [comment]
we could alter `style.css` to have links in black (or some shade of grey, or dark blue/green)... not as pleasing aesthetically, but would resolve the issue.

```
# style.css
.nav-link{
    color:white !important;
}
```

<img width="549" alt="image" src="https://github.com/user-attachments/assets/7d7f3849-8f88-49be-ace5-8519b428f18b">

```
# style.css
.nav-link{
    color:black !important;
}
```

<img width="550" alt="image" src="https://github.com/user-attachments/assets/15b60eef-4ba9-4122-b937-a49af8de7fb0">

**Comment by rcastelo** [comment]
Thanks Helena, indeed the white color of the sections is problematic when browsing the page in a small device that makes the the left white end of the background gradient overlap more with those titles. Writing them in black could be a solution, but what about making the grading end in a color that is not white?

Anyway, this issue was not about this problem, which is also a problem, but about another problem. If you click on the SPEAKERS section, and hover the mouse over the top right floating menu, you will notice that the speakers names should appear on that menu to allow you jump directly into any of them, but you don't see them because when unhovered, they are written in white, which is the color of the background. I guess there must be a way to change that white color of the floating menu to a non-white color.

**Comment by HelenaLC** [comment]
Aha, I see. I'll look into it.

**Comment by HelenaLC** [comment]
should be resolved now with a couple lines of CSS... let me know if it's satisfactory, or feel free to alter the style!

**Comment by rcastelo** [comment]
Great!! Thank you so much! I'll leave this issue open until we decide whether we do something about the other problem we initially discussed.

**Comment by HelenaLC** [comment]
Alright, I pushen an (I think elegant) fix where we don't have to cut down on aesthetics, but unfolding the hamburger menu on the right... screenshot from my phone:
<img width="365" alt="image" src="https://github.com/user-attachments/assets/b362ec45-fbcf-4a60-b654-338a62e299e8">
